'use client';

export default function InvoicePreview({ invoice }) {
  if (!invoice) return null;

  return (
    <div className="ngv-card">
      <div className="p-6">
        <div className="flex justify-between items-start mb-6">
          <div className="flex items-center gap-3">
            <img src="/logo.png" alt="NGV Logo" className="w-10 h-10 rounded-xl object-cover" />
            <div>
              <h2 className="text-xl font-bold text-surface-900">Nzelu Global Ventures</h2>
              <p className="text-xs text-surface-500">Tarpaulins, Carpets, Centre Rugs, Artificial Grass &amp; Tent Installations</p>
            </div>
          </div>
          <div className="text-right">
            <h3 className="text-lg font-bold text-ngv-700">{invoice.invoiceCode}</h3>
            <p className="text-xs text-surface-500">{new Date(invoice.date).toLocaleDateString()}</p>
          </div>
        </div>

        <div className="mb-4 p-3 bg-surface-50 rounded-xl">
          <p className="text-xs font-medium text-surface-500">Bill To:</p>
          <p className="font-semibold">{invoice.customerSnapshot?.name || invoice.billTo || 'Walk-in Customer'}</p>
          {invoice.customerSnapshot?.telephone && <p className="text-sm text-surface-600">{invoice.customerSnapshot.telephone}</p>}
        </div>

        <table className="ngv-table mb-4">
          <thead>
            <tr><th className="w-10">#</th><th>Description</th><th className="text-center w-16">Qty</th><th className="text-right w-24">Price</th><th className="text-right w-24">Total</th></tr>
          </thead>
          <tbody>
            {invoice.items?.map((item, i) => (
              <tr key={i}>
                <td className="text-center text-surface-500">{i + 1}</td>
                <td className="text-sm">{item.description}</td>
                <td className="text-center text-sm">{item.quantity}</td>
                <td className="text-right text-sm">₦{item.unitPrice?.toLocaleString()}</td>
                <td className="text-right text-sm font-medium">₦{item.total?.toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="flex justify-end">
          <div className="w-64 space-y-1 text-sm">
            <div className="flex justify-between"><span className="text-surface-500">Subtotal</span><span>₦{invoice.subtotal?.toLocaleString()}</span></div>
            <div className="border-t pt-1 flex justify-between font-bold text-base"><span>Grand Total</span><span className="text-ngv-800">₦{invoice.grandTotal?.toLocaleString()}</span></div>
          </div>
        </div>

        {invoice.type === 'proforma' && (
          <div className="mt-4 p-3 bg-ngv-50 rounded-lg border border-ngv-200">
            <p className="text-xs font-semibold text-ngv-800">Account: 2284429344 - Nzelu Akachukwu (Zenith Bank)</p>
          </div>
        )}

        <div className="mt-4 pt-3 border-t border-surface-100 text-center text-xs text-surface-400">
          Generated by NGV ERP · {invoice.createdBy?.name || 'System'} · {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}
